on: [push]
name: "xcvbn"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    steps:
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: myregvivek12.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t myregvivek12.azurecr.io/sample_image:${{ github.sha }}
        docker push myregvivek12.azurecr.io/sample_image:${{ github.sha }}

    - name: Set Web App ACR authentication
      uses: Azure/appservice-settings@v1
      with: 
        app-name: myappvivek22
        app-settings-json: | 
          [
            {
              "name": "DOCKER_REGISTRY_SERVER_URL",
              "value": "myregvivek12.azurecr.io",
              "slotSetting": false
            },
            {
              "name": "DOCKER_REGISTRY_SERVER_USERNAME",
              "value": "${{ secrets.REGISTRY_USERNAME }}",
              "slotSetting": false
            },
            {
              "name": "DOCKER_REGISTRY_SERVER_PASSWORD",
              "value": "${{ secrets.REGISTRY_PASSWORD }}",
              "slotSetting": false
            }            
          ]
      
    - uses: azure/webapps-deploy@v2
      with:
        app-name: myappvivek22
        images: myregvivek12.azurecr.io/sample_image:${{ github.sha }}
